apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Tamaño del almacenamiento que necesitas
